Add redis based adapter
joshleblanc/view_component_reflex pull request #25
Opened 2020-10-14 23:59 UTC by sebyx07

uses hmset and hgetall to reduce the number of operations.

also added `#optimized_store_to_redis` because I've seen multiple calls to `#store_state` on the first render.
I'm using it with anycable atm

2020-10-15 00:02 UTC, sebyx07 commented
![screen22](https://user-images.githubusercontent.com/5052549/96057950-05285a00-0e82-11eb-8e4d-4a0d2306465f.jpg)

with debug on

2020-10-15 10:04 UTC, joshleblanc requested changes

2020-10-15 10:04 UTC, joshleblanc commented on lib/view_component_reflex/state_adapter/redis.rb
> +          [k, v.to_json]
This to_json call and the corresponding parse would prevent a user from storing a model in state, and operating on it as if it was an instance variable. Instead, they would be operating on a hash.

The todo component is a good example in the expo: https://github.com/joshleblanc/view_component_reflex_expo/blob/master/app/components/todo_component.rb

What we could do instead is dump the object, which is what the session does by default.

```suggestion
          [k, Marshal.dump(v)]
```

2020-10-15 10:04 UTC, joshleblanc commented on lib/view_component_reflex/state_adapter/redis.rb
> +          [k, JSON.parse(v)]
This is a sister comment to the `to_json` one

```suggestion
          [k, Marshal.load(v)]
```

2020-10-15 10:04 UTC, joshleblanc commented on README.md
> +This is also the recommended way if you using it AnyCable.
```suggestion
This is the recommended adapter if you are using AnyCable.
```

2020-10-15 10:05 UTC, joshleblanc commented
Thanks so much for this!

I installed your branch into the expo project and played around with it, and left some comments about things I came across.

2020-10-17 09:27 UTC, sebyx07 commented
@joshleblanc can we get merged? Ty!

2020-10-17 10:22 UTC, merged